"""Users w/Funds.

Revision ID: 40da17247ba5
Revises: 612714157371
Create Date: 2022-06-06 13:19:32.500077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40da17247ba5'
down_revision = '612714157371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('funds', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'funds')
    # ### end Alembic commands ###
