"""fix funds

Revision ID: 7f073997f7b7
Revises: c1aa0a795bbe
Create Date: 2022-06-06 12:28:41.348101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f073997f7b7'
down_revision = 'c1aa0a795bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('capital', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'funds', 'users', ['user_id'], ['id'])
    op.drop_column('funds', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'funds', type_='foreignkey')
    op.drop_column('funds', 'capital')
    # ### end Alembic commands ###
